### ISSUE TITLE
Backend not working

### ISSUE THREAD

**Issue by franciscof5** [fariasmateuss/tindev#57]
[nodemon] watching: *.*
[nodemon] starting `node src/server.js`
(node:30894) Warning: Accessing non-existent property 'count' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:30894) Warning: Accessing non-existent property 'findOne' of module exports inside circular dependency
(node:30894) Warning: Accessing non-existent property 'remove' of module exports inside circular dependency
(node:30894) Warning: Accessing non-existent property 'updateOne' of module exports inside circular dependency
(node:30894) UnhandledPromiseRejectionWarning: Error: querySrv ENOTFOUND _mongodb._tcp.0.0.0.0
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:203:19)
(node:30894) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:30894) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by franciscof5** [comment]
node --trace-warnings ...internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module '/var/www/tinder/tindev/backend/...'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
